name: Backend API CI
on:
  push:
    paths:
      - 'backend-api/**'
  pull_request:
    paths:
      - 'backend-api/**'
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend-api
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: pytest
      - name: Lint (flake8)
        run: |
          pip install flake8
          flake8 app/ --max-line-length=120 